apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapcast # kpt-set: ${name}
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: SNAPSERVER_SOUND_TEST
          value: "true"
