apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /snapcast
  name: snapcast # kpt-set: ${name}
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|default|snapcast'
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: SNAPSERVER_SOUND_TEST
          value: "true"
