apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /blueprint
  name: snapcast # kpt-set: ${name}
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|default|blueprint'
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          # Force snapserver to run on the master node.
          # This is to
          #   a) store the settings there (PersistentVolume)
          #   b) avoid additional network traffic from mopidy and to snapcast.
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - "true"
      containers:
      - name: app
        envFrom:
        - secretRef:
            name: ${APP_NAME:=app}-defaultconfig
        - secretRef:
            name: ${APP_CONFIG_SECRET_NAME:=app-defaultconfig}
