apiVersion: apps/v1
kind: DaemonSet
metadata: # kpt-merge: /snapcast-client
  name: snapcast-client
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|DaemonSet|default|snapcast-client'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: speaker
  template:
    metadata:
      labels:
        app.kubernetes.io/component: speaker
    spec:
      serviceAccountName: snapcast-client
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      terminationGracePeriodSeconds: 1
      containers:
      - name: snapclient
        image: ghcr.io/mgoltzsche/snapcast-client:0.3.4 # kpt-set: ${client-image}:${version}
        env:
        - name: SNAPCLIENT_K8S_SERVICE
          value: snapcast
        - name: SNAPCLIENT_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 200m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 32Mi
        securityContext:
          privileged: true
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: dev-snd
          mountPath: /dev/snd
        - name: run
          mountPath: /host/run
        - name: etc
          mountPath: /host/etc
          readOnly: true
      volumes:
      - name: dev-snd
        hostPath:
          path: /dev/snd
      - name: run
        hostPath:
          path: /run
      - name: etc
        hostPath:
          path: /etc
