apiVersion: apps/v1
kind: DaemonSet
metadata: # kpt-merge: /snapcast-client
  name: snapcast-client
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|DaemonSet|default|snapcast-client'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: speaker
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "100%"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: speaker
    spec:
      serviceAccountName: snapcast-client
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 1
      containers:
      - name: snapclient
        image: ghcr.io/mgoltzsche/snapcast-client:0.5.1 # kpt-set: ${client-image}:${version}
        env:
        - name: SNAPCLIENT_HOST
          value: snapcast
        - name: SNAPCLIENT_HOSTID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            cpu: 200m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 32Mi
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 29
        volumeMounts:
        - name: dev-snd
          mountPath: /dev/snd
        - name: run
          mountPath: /host/run
        - name: etc
          mountPath: /host/etc
          readOnly: true
      volumes:
      - name: dev-snd
        hostPath:
          path: /dev/snd
          type: Directory
      - name: run
        hostPath:
          path: /run
      - name: etc
        hostPath:
          path: /etc
