name: Build
on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
    - main
    # Publish `v1.2.3` tags as releases.
    #tags:
    #- v*
    # Build pull request against the `main` branch.
    #pull_request:
    #  branches:
    #  - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - name: Build container image
      run: make image
    - name: Log into GitHub registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      if: github.ref == 'refs/heads/main'
    - name: Push image and update tag in manifests if releasable commit exists
      id: publish
      run: make release-maybe
      if: github.ref == 'refs/heads/main'
    - name: Create release
      if: steps.publish.outputs.pushed
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        prerelease: true
